### ISSUE TITLE
`FileNotFoundError`  `python continuum_snake.py`

### ISSUE THREAD

**Issue by dvogureckiy99** [GazzolaLab/PyElastica#323]
**Describe the bug**
I tried to run `continuum_snake_render.py` example

**To Reproduce**
First script goes well. 
```
python continuum_snake.py        
Total steps 220199
100%|█████████████████████████████████████████████████████████████████████| 220199/220199 [01:26<00:00, 2549.20it/s]
Final time of simulation is :  11.009999999978538
Datafile Created
```
But next bad:
```py
python continuum_snake_render.py 
```
```bash
Scripting: 100%|█████████████████████████████████████████████████████████████████| 220/220 [00:00<00:00, 561.22it/s]
Rendering:   0%|                                                                            | 0/440 [00:00<?, ?it/sm 
ultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\dvogureckiy99\miniconda3\envs\PyElastica\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\dvogureckiy99\2_Education\ITMO\DMS\elastica\PyElastica\examples\Visualization\_povmacros.py", line 126, in render
    process = subprocess.Popen(
  File "C:\Users\dvogureckiy99\miniconda3\envs\PyElastica\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dvogureckiy99\miniconda3\envs\PyElastica\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
"""
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "continuum_snake_render.py", line 164, in <module>
    for message in p.imap_unordered(func, batch):
  File "C:\Users\dvogureckiy99\miniconda3\envs\PyElastica\lib\multiprocessing\pool.py", line 868, in next
    raise value
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Rendering:   0%|                                                                            | 0/440 [00:02<?, ?it/s]
```

**Environment**
- Python 3.8
- Numpy as in dependencies
- PyElastica last
- OS Windows 10, Device Lenovo IdeaPad 310-ISK

**Comment by bhosale2** [comment]
hi @dvogureckiy99 the `ContinuumSnakeCase` has no file called `continuum_snake_render.py`. Hence you get the `FileNotFoundError`. Please re check the names of existing scripts before running them. @armantekinalp feel free to close this issue.
